// Product data lives in one place, making it easy to add or edit products.
const products = [
  {id:1,name:'Linen Resort Shirt',category:'Men',description:'Breathable linen with a relaxed tailored fit.',price:58,oldPrice:76,rating:4.8,image:'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=700&q=80'},
  {id:2,name:'Everyday Leather Sneaker',category:'Men',description:'Minimal full-grain leather made for daily wear.',price:89,oldPrice:120,rating:4.7,image:'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=700&q=80'},
  {id:3,name:'Tailored Wide-Leg Trousers',category:'Women',description:'Fluid, flattering and effortlessly polished.',price:68,oldPrice:89,rating:4.9,image:'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=700&q=80'},
  {id:4,name:'Cloud Knit Cardigan',category:'Women',description:'A soft textured layer for every season.',price:64,oldPrice:82,rating:4.6,image:'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=700&q=80'},
  {id:5,name:'Studio Wireless Headphones',category:'Electronics',description:'Immersive sound with all-day comfort.',price:129,oldPrice:169,rating:4.9,image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=80'},
  {id:6,name:'Pocket Smart Speaker',category:'Electronics',description:'Room-filling sound in a compact form.',price:74,oldPrice:94,rating:4.5,image:'https://images.unsplash.com/photo-1589003077984-894e133dabab?auto=format&fit=crop&w=700&q=80'},
  {id:7,name:'The Weekender Tote',category:'Accessories',description:'Spacious, structured, and ready to go.',price:78,oldPrice:99,rating:4.8,image:'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=700&q=80'},
  {id:8,name:'Classic Gold Timepiece',category:'Accessories',description:'Timeless detailing for a refined finish.',price:112,oldPrice:145,rating:4.7,image:'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=700&q=80'},
  {id:9,name:'Sculptural Table Lamp',category:'Home & Lifestyle',description:'A warm glow and quiet statement for your space.',price:96,oldPrice:125,rating:4.8,image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=80'},
  {id:10,name:'Ribbed Glass Carafe',category:'Home & Lifestyle',description:'A beautifully simple addition to the table.',price:35,oldPrice:45,rating:4.6,image:'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=700&q=80'},
  {id:11,name:'Organic Cotton Tee',category:'Men',description:'The elevated basic you will reach for often.',price:32,oldPrice:42,rating:4.7,image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=80'},
  {id:12,name:'Soft Leather Crossbody',category:'Women',description:'Compact design, generous everyday utility.',price:84,oldPrice:109,rating:4.9,image:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=700&q=80'}
];
let activeCategory='All', searchTerm='', sortMode='featured', detailQuantity=1;
let cart=JSON.parse(localStorage.getItem('neelamCart'))||[];
let wishlist=JSON.parse(localStorage.getItem('neelamWishlist'))||[];
const $=selector=>document.querySelector(selector);
const money=value=>`$${value.toFixed(2)}`;
function save(){localStorage.setItem('neelamCart',JSON.stringify(cart));localStorage.setItem('neelamWishlist',JSON.stringify(wishlist));}
function renderProducts(){let items=products.filter(p=>(activeCategory==='All'||p.category===activeCategory)&&p.name.toLowerCase().includes(searchTerm));if(sortMode==='price-low')items.sort((a,b)=>a.price-b.price);if(sortMode==='price-high')items.sort((a,b)=>b.price-a.price);if(sortMode==='rating')items.sort((a,b)=>b.rating-a.rating);$('#productCount').textContent=`${items.length} product${items.length!==1?'s':''}`;$('#productGrid').innerHTML=items.length?items.map(p=>`<article class="product-card"><div class="product-image" data-detail="${p.id}"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="discount">${Math.round((1-p.price/p.oldPrice)*100)}% OFF</span><button class="wishlist ${wishlist.includes(p.id)?'active':''}" data-wish="${p.id}" aria-label="Add ${p.name} to wishlist">${wishlist.includes(p.id)?'♥':'♡'}</button></div><div class="product-info"><p class="product-category">${p.category}</p><h3 class="product-title" data-detail="${p.id}">${p.name}</h3><p class="product-description">${p.description}</p><div class="product-meta"><div class="prices"><span class="price">${money(p.price)}</span><span class="old-price">${money(p.oldPrice)}</span></div><span class="rating">★ ${p.rating}</span></div><button class="button button-dark add-button" data-add="${p.id}">Add to bag</button></div></article>`).join(''):'<p class="muted">No products match your search. Try another term.</p>';}
function addToCart(id,quantity=1){const existing=cart.find(item=>item.id===id);if(existing)existing.quantity+=quantity;else cart.push({id,quantity});save();renderCart();}
function renderCart(){const totalItems=cart.reduce((sum,item)=>sum+item.quantity,0), total=cart.reduce((sum,item)=>sum+products.find(p=>p.id===item.id).price*item.quantity,0);$('#cartCount').textContent=totalItems;$('#cartTotal').textContent=money(total);$('#cartItems').innerHTML=cart.length?cart.map(item=>{const p=products.find(product=>product.id===item.id);return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>${money(p.price)}</p><div class="quantity-controls"><button data-change="${p.id}" data-step="-1" aria-label="Decrease quantity">−</button><span>${item.quantity}</span><button data-change="${p.id}" data-step="1" aria-label="Increase quantity">+</button></div></div><button class="remove-item" data-remove="${p.id}">Remove</button></div>`}).join(''):'<p class="empty-cart">Your bag is waiting for something special.</p>';}
function openDetail(id){const p=products.find(product=>product.id===id);detailQuantity=1;$('#modalContent').innerHTML=`<div class="modal-layout"><img src="${p.image}" alt="${p.name}"><div class="modal-info"><p class="eyebrow">${p.category.toUpperCase()}</p><h2>${p.name}</h2><div class="rating">★ ${p.rating} / 5.0</div><p>${p.description}</p><p class="modal-price">${money(p.price)} <del>${money(p.oldPrice)}</del></p><div class="modal-actions"><div class="detail-quantity"><button id="detailMinus">−</button><span id="detailQty">1</span><button id="detailPlus">+</button></div><button class="button button-dark" id="detailAdd">Add to bag</button></div></div></div>`;$('#productModal').showModal();$('#detailMinus').onclick=()=>updateDetailQuantity(-1);$('#detailPlus').onclick=()=>updateDetailQuantity(1);$('#detailAdd').onclick=()=>{addToCart(id,detailQuantity);$('#productModal').close();openCart();};}
function updateDetailQuantity(step){detailQuantity=Math.max(1,detailQuantity+step);$('#detailQty').textContent=detailQuantity;}
function openCart(){$('#cartPanel').classList.add('open');$('#overlay').classList.add('visible');$('#cartPanel').setAttribute('aria-hidden','false');}
function closeCart(){$('#cartPanel').classList.remove('open');$('#overlay').classList.remove('visible');$('#cartPanel').setAttribute('aria-hidden','true');}
// Event delegation keeps dynamically rendered product buttons interactive.
$('#productGrid').addEventListener('click',e=>{const id=Number(e.target.closest('[data-add],[data-wish],[data-detail]')?.dataset.add||e.target.closest('[data-add],[data-wish],[data-detail]')?.dataset.wish||e.target.closest('[data-add],[data-wish],[data-detail]')?.dataset.detail);if(!id)return;if(e.target.closest('[data-add]'))addToCart(id);else if(e.target.closest('[data-wish]')){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save();renderProducts();}else openDetail(id);});
$('#cartItems').addEventListener('click',e=>{const id=Number(e.target.dataset.change||e.target.dataset.remove);if(e.target.dataset.remove){cart=cart.filter(item=>item.id!==id);}if(e.target.dataset.change){const item=cart.find(item=>item.id===id);item.quantity+=Number(e.target.dataset.step);if(item.quantity<1)cart=cart.filter(item=>item.id!==id);}save();renderCart();});
$('#filterPills').addEventListener('click',e=>{if(!e.target.matches('button'))return;activeCategory=e.target.dataset.category;document.querySelectorAll('#filterPills button').forEach(b=>b.classList.toggle('active',b===e.target));renderProducts();});
document.querySelectorAll('.category-card').forEach(button=>button.addEventListener('click',()=>{activeCategory=button.dataset.category;document.querySelectorAll('#filterPills button').forEach(b=>b.classList.toggle('active',b.dataset.category===activeCategory));renderProducts();$('#shop').scrollIntoView();}));
$('#searchInput').addEventListener('input',e=>{searchTerm=e.target.value.trim().toLowerCase();renderProducts();});$('#sortSelect').addEventListener('change',e=>{sortMode=e.target.value;renderProducts();});$('#cartOpen').onclick=openCart;$('#cartClose').onclick=closeCart;$('#overlay').onclick=closeCart;$('.modal-close').onclick=()=>$('#productModal').close();$('#menuToggle').onclick=()=>{const open=$('#navLinks').classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',open);};document.querySelectorAll('#navLinks a').forEach(a=>a.onclick=()=>$('#navLinks').classList.remove('open'));
$('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();const email=$('#emailInput');const message=$('#newsletterMessage');if(!email.validity.valid){message.textContent='Please enter a valid email address.';message.style.color='#9c3434';return;}message.textContent='Thank you — you are on the list!';message.style.color='#355e3b';email.value='';});
$('#year').textContent=new Date().getFullYear();renderProducts();renderCart();
